# General Config
reference: "/home/mateo/RefGenomes/GCF_000001405.40/GCF_000001405.40_GRCh38.p14_genomic.fna"
data_root: "/mnt/wwn-0x5002538f42211069-part2/AlgebraBioinfLab/SequencingData/UltraLong"
outdir: "/home/mateo/PycharmProjects/NanoporePipeline/OUTPUT"
fastq_subpath: "basecalling/pass"

# Methylation calling with modkit
modkit_threshold_c: "C:0.98"
modkit_threshold_a: "A:0.98"
modkit_docker: "ontresearch/modkit:latest"
modkit_interval_bp: 100000
promoters_bed_file: "/home/mateo/RefGenomes/GCF_000001405.40/promoters_1kb.pc.bed"
modkit_chunk_intervals: 6
methylation_markers: "methylation_markers.csv"


# Clair3 Config
clair3_docker_image: "hkubal/clair3:latest"
clair3_gpus: "all"
clair3_model_path: "r1041_e82_400bps_sup_v520" #r1041_e82_400bps_hac_v500,r1041_e82_400bps_sup_v410,r1041_e82_400bps_hac_v410
clair3_model_dir: "/home/mateo/PycharmProjects/NanoporePipeline/models/"
target_bed: "/home/mateo/RefGenomes/GCF_000001405.40/gene_anotation.bed"

# DP=6 this requires â‰¥2 ALT reads (2/6=0.33), which dramatically reduces
# single-read SNP false positives that often slip through the defaults (defaults are ~0.08 for SNPs)
clair3_min_mq: 20
clair3_min_coverage: 5
clair3_qual: 12
clair3_indel_min_af: 0.2
clair3_snp_min_af: 0.25


#Longshot
longshot_docker_image: "quay.io/biocontainers/longshot:1.0.0--h8dc4d9d_3"
longshot_min_af: 0.2
longshot_max_cov: auto
longshot_min_mq: 20

#Sniffles2
sniffles_docker_image: "quay.io/biocontainers/sniffles:2.6.3--pyhdfd78af_0"
sniffles_min_support : 3
sniffles_minsvlen: 50
sniffles_mapq: 25
sniffles_qc_coverage : 2
sniffles_tandem_repeats_bed: "/home/mateo/RefGenomes/GCF_000001405.40/human_GRCh38_TANDEM_REPEATS.trf.bed"
